#!/usr/bin/env python3
"""Build a verse-by-verse index into each chapter's README.md.

For every chapter folder, this scans the translation files present
(WEB.md, KJV.md, ASV.md, BBE.md, ...) and writes a "Verses" table into
README.md: one row per verse, with a link to that verse in EVERY translation
available in the folder.

It is regenerate-safe. The generated table lives between markers:

    <!-- BEGIN VERSE-INDEX (auto-generated ...) -->
    ...table...
    <!-- END VERSE-INDEX -->

On a stub README ("# Read Me") it writes a fresh README: title + verse index +
the standard study-notes template (Key Verses / Summary / Notes / Cross
References / Questions). On a README that already has notes, it only replaces
the marked block (or inserts it just under the first heading) and leaves your
notes untouched.

Anchors: the translation files carry <a id="vN"></a> tags per verse (written by
fetch_scripture.py), so links like WEB.md#v3 jump straight to verse 3.

Usage (mirrors fetch_scripture.py):
    python scripts/build_readme_index.py scripture/19-Psalms
    python scripts/build_readme_index.py scripture/19-Psalms --chapters 1-3
    python scripts/build_readme_index.py --all

Standard library only. Runs the same on Windows (python) and WSL/Linux (python3).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPTURE = REPO_ROOT / "scripture"

BEGIN = "<!-- BEGIN VERSE-INDEX (auto-generated by scripts/build_readme_index.py — safe to regenerate) -->"
END = "<!-- END VERSE-INDEX -->"

# Preferred column order; anything else is appended alphabetically.
VERSION_ORDER = ["WEB", "KJV", "ASV", "BBE", "YLT", "KJVA", "AKJV", "WB", "DRA",
                 "TYNDALE", "WEYMOUTH", "WYCLIFFE"]

# Files in a chapter folder that are NOT translation texts.
NON_VERSION = {"README.md", "notes.md", "NOTES.md"}

STUDY_TEMPLATE = """## Key Verses

<!-- List verses that stand out from this chapter. -->

## Summary

<!-- Brief overview of what happens in this chapter. -->

## Notes

<!-- Personal observations, insights, and reflections. -->

## Cross References

<!-- Links to related passages in other books/chapters. -->

## Questions

<!-- Things to revisit, study further, or discuss. -->
"""


def book_number(book_dir: Path):
    m = re.match(r"^(\d+)-", book_dir.name)
    return int(m.group(1)) if m else None


def chapter_folders(book_dir: Path):
    found = []
    for child in book_dir.iterdir():
        if child.is_dir() and re.search(r"-(\d+)$", child.name):
            found.append((int(re.search(r"-(\d+)$", child.name).group(1)), child))
    found.sort(key=lambda t: t[0])
    return found


def version_files(folder: Path):
    """Return [(label, path)] for translation files, in preferred order."""
    files = [p for p in folder.glob("*.md") if p.name not in NON_VERSION]
    labels = {p.stem: p for p in files}
    ordered = [s for s in VERSION_ORDER if s in labels]
    ordered += sorted(s for s in labels if s not in VERSION_ORDER)
    return [(s, labels[s]) for s in ordered]


def verses_in(path: Path):
    text = path.read_text(encoding="utf-8")
    nums = re.findall(r'id="v(\d+)"', text)
    if not nums:  # fall back to the bold-number format if anchors are missing
        nums = re.findall(r"^\*\*(\d+)\*\*", text, re.M)
    return {int(n) for n in nums}


def chapter_ref(folder: Path, versions):
    """Human title like 'Psalms 1' — from a version file header, else the folder."""
    if versions:
        first = versions[0][1].read_text(encoding="utf-8").splitlines()[0]
        m = re.match(r"#\s*(.+?)\s+—", first)
        if m:
            return m.group(1).strip()
    m = re.match(r"^(.*)-(\d+)$", folder.name)
    if m:
        return f"{m.group(1).replace('-', ' ')} {int(m.group(2))}"
    return folder.name


def build_block(ref: str, versions):
    labels = [lbl for lbl, _ in versions]
    all_verses = sorted(set().union(*[verses_in(p) for _, p in versions])) if versions else []
    verse_sets = {lbl: verses_in(p) for lbl, p in versions}

    read_line = "📖 **Read the full chapter:** " + " · ".join(
        f"[{lbl}]({lbl}.md)" for lbl in labels
    )
    header = "| # | " + " | ".join(labels) + " |"
    sep = "|---|" + "|".join("---" for _ in labels) + "|"
    rows = []
    for v in all_verses:
        cells = []
        for lbl in labels:
            cells.append(f"[{lbl}]({lbl}.md#v{v})" if v in verse_sets[lbl] else "—")
        rows.append(f"| {v} | " + " | ".join(cells) + " |")

    body = [BEGIN, "", read_line, "", f"## Verses ({len(all_verses)})", "",
            header, sep, *rows, "", END]
    return "\n".join(body)


def is_stub(content: str) -> bool:
    s = content.strip().lower()
    return s in ("", "# read me", "# read me.", "# readme")


def update_readme(folder: Path) -> str:
    versions = version_files(folder)
    if not versions:
        return "skip (no translation files)"
    ref = chapter_ref(folder, versions)
    block = build_block(ref, versions)
    readme = folder / "README.md"
    content = readme.read_text(encoding="utf-8") if readme.exists() else ""

    if BEGIN in content and END in content:
        pre = content[: content.index(BEGIN)]
        post = content[content.index(END) + len(END):]
        new = pre + block + post
        action = "updated index"
    elif is_stub(content):
        new = f"# {ref}\n\n{block}\n\n{STUDY_TEMPLATE}"
        action = "created from stub"
    else:
        lines = content.splitlines()
        idx = next((i for i, l in enumerate(lines) if l.startswith("# ")), None)
        if idx is None:
            new = f"# {ref}\n\n{block}\n\n{content}"
        else:
            head = "\n".join(lines[: idx + 1])
            tail = "\n".join(lines[idx + 1:])
            new = f"{head}\n\n{block}\n\n{tail.lstrip()}"
        action = "inserted index (notes preserved)"

    if not new.endswith("\n"):
        new += "\n"
    readme.write_text(new, encoding="utf-8", newline="\n")
    return f"{action} ({len(versions)} versions)"


def parse_range(spec):
    if not spec:
        return None
    if "-" in spec:
        lo, hi = spec.split("-", 1)
        return range(int(lo), int(hi) + 1)
    n = int(spec)
    return range(n, n + 1)


def main(argv=None):
    p = argparse.ArgumentParser(description="Build verse-index tables into chapter READMEs.")
    p.add_argument("book", nargs="?", help="path to a book folder, e.g. scripture/19-Psalms")
    p.add_argument("--all", action="store_true", help="process every book under scripture/")
    p.add_argument("--chapters", help="chapter or range, e.g. 1 or 1-3 (single book)")
    args = p.parse_args(argv)

    if not args.all and not args.book:
        p.error("give a book folder or --all")
    chap_range = parse_range(args.chapters)

    if args.all:
        books = sorted(d for d in SCRIPTURE.iterdir() if d.is_dir() and book_number(d) is not None)
    else:
        bdir = Path(args.book)
        if not bdir.is_absolute():
            bdir = Path.cwd() / bdir
        if not bdir.exists():
            bdir = REPO_ROOT / args.book
        books = [bdir.resolve()]

    total = 0
    for bdir in books:
        print(f"-> {bdir.name}")
        for chapter, folder in chapter_folders(bdir):
            if chap_range is not None and chapter not in chap_range:
                continue
            result = update_readme(folder)
            total += 1
            if not args.all:
                print(f"   {folder.name}: {result}")
        if args.all:
            print(f"   processed {bdir.name}")
    print(f"\nDONE. READMEs processed: {total}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
